// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:879f0c2f-d0d3-4498-b65d-4a76ab4aa7d9',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'dianaparvuoficialro-hosting-mobilehub-477329340',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd19tslk2eh2unv.cloudfront.net',
    'aws_mobile_analytics_app_id': '12bc47812e6e4fda810d6adfe7a0a8eb',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '8234743a-e45f-4ed9-8532-e322548bf19c',
    'aws_project_name': 'dianaparvuoficial.ro',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'dianaparvuoficialro-mobilehub-477329340',
}

export default awsmobile;
